### ISSUE TITLE
missing guava dependency with sbt

### ISSUE THREAD

**Issue by syves** [killbilling/recurly-java-library#95] opened 2016-02-05 23:03 UTC
When I pull in the library through sbt 
by adding to build.sbt ->
libraryDependencies += "com.ning.billing" % "recurly-java-library" % "0.4.0"

I get this error:

java.lang.NoClassDefFoundError: com/google/common/io/Resources)
java.lang.NoClassDefFoundError: com/google/common/io/Resources
at com.ning.billing.recurly.RecurlyClient.buildUserAgent(RecurlyClient.java:1045)
at com.ning.billing.recurly.RecurlyClient.<init>(RecurlyClient.java:144)

I had to fish around and finally determined I needed ->
libraryDependencies += "com.google.guava" % "guava" % "18.0"

I'm not sure why this isn't included, or pulled in properly. FYI!

**Comment by pierre** [comment] 2016-02-08 15:48
Duplicate of https://github.com/killbilling/recurly-java-library/issues/73.

**Closed by pierre** 2016-02-08 15:48 UTC
Labels: duplicate

**Comment by syves** [comment] 2016-02-08 17:42
Oh ok!
