### ISSUE TITLE
Missing tax fields on Invoice and Subscription

### ISSUE THREAD

**Issue by mzouitni** [killbilling/recurly-java-library#125] opened 2016-07-13 12:39 UTC
Hi folks,
As we were trying to start processing the tax related fields that recurly sends as part of the invoice and subscription we noticed that your library doesn't have support for them, any reason why that is the case?

The fields in question are: 
tax_type, tax_rate and tax_region.

Can we introduce these fields to invoice and subscription?

Thanks

**Comment by bhelx** [comment] 2016-07-14 16:59
@mzouitni  It's possible these were missed or they were added to the API and not added to this library. They should be easy to add. I'd be happy to review any PRs you may have to make this library work for your use cases.

**Comment by mzouitni** [comment] 2016-07-15 03:03
@bhelx I will make the changes

**Comment by mzouitni** [comment] 2016-07-15 14:55
@bhelx PR is created. When do you think you guys will have your next release?

**Comment by bhelx** [comment] 2016-07-15 16:03
@mzouitni I'll try to review the PR this afternoon and get it merged. It looks very straight forward.
@pierre generally handles the release schedule.

**Comment by pierre** [comment] 2016-07-15 18:02
@bhelx Once it's merged, could you re-run all regressions, including enterprise features?

Once I get the 👌, I'll cut a release.

**Comment by bhelx** [comment] 2016-07-15 18:06
@pierre sure thing 👍

**Comment by bhelx** [comment] 2017-01-16 15:15
I can't find the specific PR, but looks like this was fixed in August, 2016. Please reopen if there are still problems.

**Closed by bhelx** 2017-01-16 15:15 UTC
