### ISSUE TITLE
NoSuchMethod error when using Jackson 2.8

### ISSUE THREAD

**Issue by eodonohoe** [killbilling/recurly-java-library#187] opened 2017-05-05 16:59 UTC
```
! java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.xml.ser.ToXmlGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
! at com.ning.billing.recurly.model.jackson.RecurlyObjectsSerializer.serialize(RecurlyObjectsSerializer.java:51)
! at com.ning.billing.recurly.model.jackson.RecurlyObjectsSerializer.serialize(RecurlyObjectsSerializer.java:32)
! at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanPropertyWriter.serializeAsField(XmlBeanPropertyWriter.java:145)
! at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializerBase.serializeFields(XmlBeanSerializerBase.java:203)
! at com.fasterxml.jackson.dataformat.xml.ser.XmlBeanSerializer.serialize(XmlBeanSerializer.java:118)
! at com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider.serializeValue(XmlSerializerProvider.java:92)
! at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
! at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3057)
! at com.ning.billing.recurly.RecurlyClient.doPOST(RecurlyClient.java:1457)
! at com.ning.billing.recurly.RecurlyClient.createSubscription(RecurlyClient.java:358)
```

**Comment by bhelx** [comment] 2017-05-05 17:08
@eodonohoe Thanks for submitting. How can we go about reproducing?

**Comment by eodonohoe** [comment] 2017-05-05 17:25
I'm  pretty sure upgrading to jackson version 2.8 or newer and attempting creating a subscription will cause the problem to happen.

**Comment by bhelx** [comment] 2017-05-09 18:33
Okay, I can confirm that we don't support this yet.

@pierre how do we go about fixing this? Should we try to bump up our version of jackson?

**Comment by pierre** [comment] 2017-05-09 20:14
> how do we go about fixing this? Should we try to bump up our version of jackson?

Happy to give it a try if there's indeed a **need** to upgrade, but I don't think we should upgrade it just for the sake of upgrading it:

* Jackson XML upgrades are notoriously difficult -- we've had to work around a few things in the past because of the specific XML format Recurly returns (nothing specific to Recurly, we had an issue in the [Kill Bill Accertify plugin](https://github.com/killbill/killbill-accertify-plugin/commit/7a80a472b36f2328f773659762a950c476ef455d#diff-a20077dbddb16647049ae901bfea1ad7R60) recently as well)
* This forces all users of the client to upgrade Jackson in their application (and 2.5.0 to 2.8.x is a big upgrade, not just for the XML module)

So, thoughts?

**Comment by bhelx** [comment] 2017-05-09 20:35
@pierre I figured this was the case. Is there a way for people who are using newer versions of jackson to get around this problem? Or would they be forced to downgrade to 2.5?

**Comment by pierre** [comment] 2017-05-09 21:30
Not really, unless we were to shade Jackson in our Jar. It would make the Jar bigger, but that way, we wouldn't have these dependencies issues. We could also provide two builds, one shaded and one non-shaded.

**Comment by CookieDuck** [comment] 2017-07-19 22:31
+1 for a release that includes the preferred version of jackson with the library.  Running into a similar issue around Subscription marshaling

**Comment by jfreeby** [comment] 2017-12-20 22:30
We are also trying to upgrade to the Jackson 2.9 and see the issue.

It looks like RecurlyObjectsSerializer line 51 is where an issue is.  Apparently the method signature changed for GeneratorBase.getOutputContext.  

Does anyone know why we need to call xmlgen.getOutputContext().writeFieldName(elementName); for Jackson version 2.5?

Could we even check the type in the code as follows (this might allow support for both older and newer versions of Jackson):

        Object context = xmlgen.getOutputContext() ;
        if( context instanceof JsonWriteContext ){
        	((JsonWriteContext) context).writeFieldName(elementName);
        }

**Comment by pierre** [comment] 2018-04-23 07:13
0.15.0 has been released.

**Comment by aaron-suarez** [comment] 2018-08-22 22:18
Closing this issue because it was fixed by https://github.com/killbilling/recurly-java-library/pull/225

**Closed by aaron-suarez** 2018-08-22 22:18 UTC
