### ISSUE TITLE
Migrate to Jackson 2.4+

### ISSUE THREAD

**Issue by alex-konkov** [killbilling/recurly-java-library#66] opened 2015-01-31 17:15 UTC
It would be nice to migrate to the latest Jackson dependency. There is at least an issue with RecurlyUnitCurrency class, as follows

```Caused by: java.lang.IllegalArgumentException: Duplicate property '' for [simple type, class com.ning.billing.recurly.model.Plan$RecurlyUnitCurrency]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.addProperty(BeanDeserializerBuilder.java:160)
	...```

**Comment by pierre** [comment] 2015-02-01 21:26
There are a few issues to work through for the upgrade:

* Regarding your error, a workaround seems to be to remove `@XmlValue` from `RecurlyUnitCurrency`
* Another regression is related to `@XmlRootElement`: replacing it with `@JsonRootName` seems to work.
* Finally, it looks like there is a regression related to https://github.com/FasterXML/jackson-dataformat-xml/issues/76, causing the elements of a collection in the XML to be hardcoded to `item`. I haven't found a workaround yet.

Will try a few things and report...

**Comment by pierre** [comment] 2015-02-04 13:26
I've pushed a fix in the `jackson-2.5-upgrade` branch. Could you give it a try? I've done limited testing, but fast and integration tests seem to pass.

**Comment by alex-konkov** [comment] 2015-02-04 14:48
Thanks a lot Pierre, Transaction deserialisation appears to work fine now, as well as unit tests pass! Hopefully, the changes will be released some day.

**Comment by pierre** [comment] 2015-02-04 15:34
Regarding the merge, I'd like to see more testing first. Do you have an environment where you can let it bake for a while?

**Comment by alex-konkov** [comment] 2015-02-04 18:57
Ok, will give it a trial run. Thx.

**Comment by jkeam** [comment] 2015-07-15 18:53
+1 to this fix making its way back into master :)

**Comment by jkeam** [comment] 2015-07-15 20:15
Just noticed it looks like this was merged into master:

Merge: 515cd55 c734449
Author: Pierre-Alexandre Meyer <pierre@mouraf.org>
Date:   Sun Feb 8 15:40:58 2015 -0500

    Merge branch 'jackson-2.5-upgrade'

    Signed-off-by: Pierre-Alexandre Meyer <pierre@mouraf.org>

    Conflicts:
        src/main/java/com/ning/billing/recurly/model/Subscription.java


Any reason why this ticket isn't closed?

**Comment by pierre** [comment] 2015-07-16 12:10
I wanted to get a bit more testing, but it seems that no-one has complained yet!

**Closed by pierre** 2015-07-16 12:10 UTC

**Comment by jkeam** [comment] 2015-07-16 13:50
:+1:
