### ISSUE TITLE
Create subscription generates invalid_xml

### ISSUE THREAD

**Issue by fedepia** [killbilling/recurly-java-library#53] opened 2014-09-10 23:01 UTC
I'm testing the API and my below code generates an invalid xml error.

The code is:

    @Test
	public void testSubscribeUserToPlan()
	{
		System.setProperty("recurly.debug", "true");
		
		RecurlyClient recurlyClient = new RecurlyClient(API_KEY);
		recurlyClient.open();
		
		try 
		{
			Account acc = recurlyClient.getAccount("12312");
			
			Subscription subscriptionData = new Subscription();
			subscriptionData.setPlanCode("cs_premium");
			subscriptionData.setAccount(acc);
			subscriptionData.setCurrency("USD");
			subscriptionData.setUnitAmountInCents(1242);
            
			Subscription subscription = recurlyClient.createSubscription(subscriptionData);
			
			recurlyClient.close();
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}

And the response is:

    INFO : com.ning.billing.recurly.RecurlyClient - Msg to Recurly API [POST]:: URL : https://api.recurly.com:443/v2/subscriptions
    INFO : com.ning.billing.recurly.RecurlyClient - Payload for [POST]:: <subscription><unit_amount_in_cents>1242</unit_amount_in_cents><plan_code>cs_premium</plan_code><account><address/><adjustments/><invoices/><subscriptions/><transactions/><account_code>12312</account_code><state>closed</state><email>fedetest@cssf.com</email><first_name>Fede</first_name><last_name>Lasttestff</last_name><hosted_login_token>718556262971164f502526035aa770bf</hosted_login_token><created_at>2014-09-09T17:15:49.000-06:00</created_at></account><currency>USD</currency></subscription>
    INFO : com.ning.billing.recurly.RecurlyClient - Msg from Recurly API :: <?xml version="1.0" encoding="UTF-8"?>
    <error>
      <symbol>invalid_xml</symbol>
      <description>The provided XML was invalid.</description>
      <details>Unacceptable tag &lt;adjustments&gt;</details>
    </error>

It seems that some unneeded xml tags are being generated for empty values like adjustments.

**Comment by shrihubble** [comment] 2016-03-16 04:46
Hi @fedepia 

Did u get any solution? I am also facing the same problem.

**Comment by fedepia** [comment] 2016-03-16 14:40
@shrihubble no, I switched to the xml standard usage.

**Comment by bhelx** [comment] 2016-03-17 17:12
Closing because this is a duplicate of https://github.com/killbilling/recurly-java-library/issues/92

Let's follow the issue there

**Closed by bhelx** 2016-03-17 17:12 UTC
