### ISSUE TITLE
Unacceptable tag "adjustments"

### ISSUE THREAD

**Issue by jahskee** [killbilling/recurly-java-library#92] opened 2015-11-12 20:31 UTC
I am trying to just update the account but it returns this error Unacceptable tag adjustments

**Comment by jahskee** [comment] 2015-11-14 15:39
I see that, there is no Junit Test cases yet for getAccount(...) and updateAccount(...).

**Comment by shrihubble** [comment] 2016-03-15 10:06
Hi @jahskee 

Did u get any solution? I am also facing the same problem.

**Comment by bhelx** [comment] 2016-03-15 14:27
@shrihubble could you submit some code to help reproduce the problem? I'd be happy to take a look at it.

**Comment by jahskee** [comment] 2016-03-15 15:02
I found out a solution, by only putting values on the fields that you want to update in the value object,
so you should start with an empty account object, those that are null will not be updated.
That solved the issue.

Regards,
Jaizon

**Comment by bhelx** [comment] 2016-03-15 15:19
@jahskee some code to reproduce the problem would be helpful

**Comment by shrihubble** [comment] 2016-03-15 16:44
RecurlyClient recurlyClient = new RecurlyClient(API_KEY);
try 
{
recurlyClient.open();
Account account = recurlyClient.getAccount(accountId);
BillingInfo billingInfoData = recurlyClient.getBillingInfo(accountId);
account.setBillingInfo(billingInfoData);

Subscription subscriptionRequest = null;
subscriptionRequest.setAccount(account);
subscriptionRequest.setCurrency(currency);
subscriptionResult = recurlyClient.createSubscription(subscriptionRequest);
Subscription subscription = recurlyClient.createSubscription(subscriptionData);
catch (Exception e)
    {
        e.printStackTrace();
    }

**Comment by shrihubble** [comment] 2016-03-15 17:12
@jahskee 

I am facing this problem when creating a subscription. Please see my code above.

**Comment by bhelx** [comment] 2016-03-15 17:14
@shrihubble 

I'm assuming this is an existing Account with an existing billing info? If so I don't think you need to pull down and set the billing info again.

I'm also confused by where `subscriptionData` is coming from and also it seems that you haven't set a plan code on the subscription.

**Comment by bhelx** [comment] 2016-03-15 17:18
@shrihubble

See this integration test for guidance on how to create subscriptions:

https://github.com/killbilling/recurly-java-library/blob/master/src/test/java/com/ning/billing/recurly/TestRecurlyClient.java#L428

**Comment by shrihubble** [comment] 2016-03-15 17:18
@bhelx 
I have updated the code. Even after removing the billing info, same problem is coming.
I actually want to use billing info from the secret token
` BillingInfo bInfo = new BillingInfo();
  bInfo.setTokenId(secretToken);
account.setBillingInfo(bInfo);`

**Comment by shrihubble** [comment] 2016-03-15 17:21
https://github.com/killbilling/recurly-java-library/blob/master/src/test/java/com/ning/billing/recurly/TestRecurlyClient.java#L428

In this link they are actually creating new account and new billing info, not fetching the existing.

**Comment by shrihubble** [comment] 2016-03-16 04:54
@bhelx 

Any help?

**Comment by bhelx** [comment] 2016-03-17 17:11
@shrihubble sorry I wasn't available yesterday.

It seems to me like maybe the Account object is serializing the adjustments tag and the API is not accepting it. Could you possibly enable debug logging with the property `Drecurly.debug=true` and paste in the xml that is being generated?

**Comment by jahskee** [comment] 2016-03-17 17:57
I posted the solution in my experience that fixed this issue.

**Comment by bhelx** [comment] 2016-03-17 18:23
@shrihubble I'm seeing that @fedepia posted the payload:

```
INFO : com.ning.billing.recurly.RecurlyClient - Msg to Recurly API [POST]:: URL : https://api.recurly.com:443/v2/subscriptions
INFO : com.ning.billing.recurly.RecurlyClient - Payload for [POST]:: <subscription><unit_amount_in_cents>1242</unit_amount_in_cents><plan_code>cs_premium</plan_code><account><address/><adjustments/><invoices/><subscriptions/><transactions/><account_code>12312</account_code><state>closed</state><email>fedetest@cssf.com</email><first_name>Fede</first_name><last_name>Lasttestff</last_name><hosted_login_token>718556262971164f502526035aa770bf</hosted_login_token><created_at>2014-09-09T17:15:49.000-06:00</created_at></account><currency>USD</currency></subscription>
INFO : com.ning.billing.recurly.RecurlyClient - Msg from Recurly API :: <?xml version="1.0" encoding="UTF-8"?>
<error>
  <symbol>invalid_xml</symbol>
  <description>The provided XML was invalid.</description>
  <details>Unacceptable tag &lt;adjustments&gt;</details>
</error>
```

**Comment by bhelx** [comment] 2016-03-17 18:33
@pierre is there a reason that these elements are being serialized this way?

```xml
<address/><adjustments/><invoices/><subscriptions/>
```

I'm assuming it's because they are either null or empty.

Would you foresee a problem with telling the XmlMapper not to serialize `RecurlyObjects` that are empty?

I'm not sure if there is an option we can set in here or if we'd need to override the serializer:

https://github.com/killbilling/recurly-java-library/blob/master/src/main/java/com/ning/billing/recurly/model/RecurlyObject.java#L70-L95

**Comment by bhelx** [comment] 2016-03-17 19:11
@shrihubble @fedepia @jahskee

If the account already exists, you only need the account code. So one way around this for now is to create some account data with only the account code (Here I am calling it `referenceAccount`).

Borrowing from test code from @fedepia https://github.com/killbilling/recurly-java-library/issues/53#issue-42471393

I made this test:

```java
    @Test
    public void testSubscribeUserToPlan()
    {

        final Account accountData = TestUtils.createRandomAccount();
        final BillingInfo billingInfoData = TestUtils.createRandomBillingInfo();
        final Plan planData = TestUtils.createRandomPlan();

        try {

            System.setProperty("recurly.debug", "true");

            final Account account = recurlyClient.createAccount(accountData);

            billingInfoData.setAccount(account);
            final BillingInfo billingInfo = recurlyClient.createOrUpdateBillingInfo(billingInfoData);

            final Plan plan = recurlyClient.createPlan(planData);

            // Create a temporary account object just holding the account code
            Account referenceAccount = new Account();
            referenceAccount.setAccountCode(account.getAccountCode());

            final Subscription subscriptionData = new Subscription();

            subscriptionData.setPlanCode(plan.getPlanCode());
            subscriptionData.setAccount(referenceAccount);
            subscriptionData.setCurrency("USD");
            subscriptionData.setUnitAmountInCents(1242);

            Subscription subscription = recurlyClient.createSubscription(subscriptionData);
            Assert.assertNotNull(subscription);
        }
        catch (Exception e)
        {
            Assert.fail(e.getMessage());
        } finally {
            recurlyClient.clearBillingInfo(accountData.getAccountCode());
            recurlyClient.closeAccount(accountData.getAccountCode());
            recurlyClient.deletePlan(planData.getPlanCode());
        }
    }
```

Let me know if that helps. I think our integration tests are not properly failing on this issue.

**Comment by pierre** [comment] 2016-03-19 19:38
> Would you foresee a problem with telling the XmlMapper not to serialize RecurlyObjects that are empty?

Nope, I think that should be fine (assuming your backend doesn't care either way). Unit tests will probably need to be updated.

I'm not quite sure how to configure the `XmlMapper` to do it though :confused:  You might have to try a few things...

**Comment by bhelx** [comment] 2016-03-19 19:53
@pierre sure thing, I'll try some stuff in a follow up.

@shrihubble @fedepia I am assuming the code I gave above should work for you so I am closing this for now. Please feel free to reopen or continue commenting if it doesn't satisfy.

**Comment by demetrio812** [comment] 2019-03-12 18:28
Hello @bhelx 
we just had the same problem and debugged it, the xml code that it send when I try to use and Account object received is giving an error, and even if we remove the adjustments from the request there are other tags that will push the server to return an error.

I've tried your solution and it works, but I think it's worth reopening this issue, unless you don't create a  sort of "request object" that we can pass to the method so it's clear we cannot pass the account itself.

Thanks,
Dem

**Comment by aaron-suarez** [comment] 2019-03-12 18:52
@demetrio812 Just so we can verify the problem is the same, could you please post your code example and the XML that's being sent to the API?

**Comment by demetrio812** [comment] 2019-03-12 20:45
Hello @aaron-suarez 
Thanks for replying, this is the code:

    val plan = recurlyClient.getPlan(planCode)
    val account = recurlyClient.createAccount(accountData)
    val subscription = createSubscription(account, plan)
    recurlyClient.createSubscription(subscription)

The last call was producing the following xml:

    <subscription xmlns="">
        <plan_code>planTest</plan_code>
        <account>
            <address>
                <address1>L28xUhEy0S</address1>
                <address2>L28xUhEy0S</address2>
                <city>L28xUhEy0S</city>
                <state>JA</state>
                <zip>94110</zip>
                <country>US</country>
                <phone>7047892040</phone>
            </address>
            <adjustments></adjustments>
            <invoices></invoices>
            <subscriptions></subscriptions>
            <transactions></transactions>
            <account_code>L28xUhEy0S</account_code>
            <state>active</state>
            <email>L28x@test.com</email>
            <first_name>L28xU</first_name>
            <last_name>L28xUh</last_name>
            <company_name>L28xUhEy0S</company_name>
            <accept_language>en-US</accept_language>
            <hosted_login_token>fdfdsfdsfsdfdfReZ5CkUuHcjyDYYL</hosted_login_token>
            <created_at>2019-03-12T18:10:00.000Z</created_at>
            <updated_at>2019-03-12T18:10:00.000Z</updated_at>
            <shipping_addresses></shipping_addresses>
            <custom_fields></custom_fields>
            <has_live_subscription>false</has_live_subscription>
            <has_active_subscription>false</has_active_subscription>
            <has_future_subscription>false</has_future_subscription>
            <has_canceled_subscription>false</has_canceled_subscription>
            <has_past_due_invoice>false</has_past_due_invoice>
            <has_paused_subscription>false</has_paused_subscription>
            <vat_number>erewrwewerI1vQt</vat_number>
            <preferred_locale>en-US</preferred_locale>
        </account>
        <currency>EUR</currency>
    </subscription>

Let me know if you need anything else

Cheers,
Dem

**Comment by aaron-suarez** [comment] 2019-04-03 16:32
@demetrio812 You have a function, apparently, called createSubscription
```java
val subscription = createSubscription(account, plan)
```
Can you please paste the code for that function?

Also, it looks like the XML you posted is the response from the server (I could be wrong on that, but I don't think the client sends a `created_at` and `updated_at` for example). It would be helpful to have the XML that is being sent by the client

**Comment by aaron-suarez** [comment] 2019-04-03 16:53
Oh, I see what's happening. You're setting the account on the new subscription as the exact account object that you get back from the API when you do `createAccount`, and that produces unacceptable XML tags. The proper use of the library is to set the reference account as displayed above. And this is confusing because it seems like there's no reason not to pass the full account object when it's really the same class.

Perhaps a better interface would involve a class called `AccountRequest` or something, and you would attach that to the subscription rather than an Account that was returned from the API. However, I don't think that it would be worth the engineering effort to do this. Something we will keep in mind as we move onto the next major version of the API.

I'll take a closer look at the problem and see if we can prevent these extra tags from serializing.

**Comment by aaron-suarez** [comment] 2019-04-03 23:15
So part of the problem is that Jackson is doing exactly what it needs to do for most use cases. In the case of `adjustments` specifically, when the library creates the Account object based on the XML from the API, it creates an empty `Adjustments` object. This class extends `ArrayList`, so you could do something like
```java
if (account.getAdjustments().isEmpty()) {
    account.setAdjustments(null);
}
```
This would prevent an empty tag from serializing. But, of course, you'd have to do that for every other invalid tag on the `Account` object.

The best solution would be to change your call to `createSubscription` like so:
```java
val accountData = new Account()
accountData.setAccountCode(account.getAccountCode())
val subscription = createSubscription(accountData, plan)
```

As I hinted at above, it's kind of a design flaw of the library to assume that the response from the API match directly to a valid request back to the API. Proper use of the library is to create a new object which will produce the XML you want to send, and in this case, you only need the account code to associate the account with a subscription. But if we were to stop serializing empty lists in general, you would run into other problems.

Suppose you have custom fields on a subscription, and you want to clear them out. You can do so by sending the following XML:
```xml
<subscription><custom_fields/></subscription>
```

Since writing empty lists is a valid use case for the library, I'm going to close this out again. This problem cannot be fixed without redesigning the library.

**Closed by aaron-suarez** 2019-04-03 23:15 UTC
